### ISSUE TITLE
How to train the ShufflenetFull.pth

### ISSUE THREAD

**Issue by Lireanstar** [sajjjadayobi/FaceLib#1]
HI,
How was the model file **ShufflenetFull.pth** trained? Thanks for informing!

**Comment by Lireanstar** [comment]
When i run the code train.py
i found 

> data = np.load('data.npy', allow_pickle=True)

how can i get the data.npy?
could you please provide the reference?or code? thanks a lot!

**Comment by sajjjadayobi** [comment]
Hi,
I put it on the repository, OK?

**Comment by sajjjadayobi** [comment]
it exist in this path AgeGender/data.npy
