### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by A-Lohse** [sajjjadayobi/FaceLib#13]
Hi great repo, 

I can't seem to find any metrics on the performance of you gender/age model. Do you know where I can find that?

cheers, 
Augeust

**Comment by sajjjadayobi** [comment]
Hi thanks, I don't test my models on benchmark datasets (just in gender/age)
the training code is [here](https://github.com/sajjjadayobi/FaceLib/blob/master/facelib/AgeGender/models/train.py)
you can train it easily with any backbone that you want and test 

please give me a 🌟 :

**Comment by A-Lohse** [comment]
Thanks for the quick reply. That sounds fine.
