### ISSUE TITLE
ShuffleneTiny model for Age-Gender estimation

### ISSUE THREAD

**Issue by dspinczyk** [sajjjadayobi/FaceLib#14]
Could you provide ShuffleneTiny model for Age-Gender estimation ? or guide how to preapare it ? 
I looked at TreB1eN / InsightFace_Pytorch and the model for mobile devices: Mobilefacenet - but as I understand it is not the same?

**Comment by sajjjadayobi** [comment]
you can train it with this [code](https://github.com/sajjjadayobi/FaceLib/blob/master/facelib/AgeGender/models/train.py)
but use Tiny instead of Full

**Comment by dspinczyk** [comment]
Thanks a lot!
________________________________
Od: Sajjad Ayobi ***@***.***>
Wysłane: środa, 24 marca 2021 07:23
Do: sajjjadayobi/FaceLib ***@***.***>
DW: Dominik Spinczyk ***@***.***>; Author ***@***.***>
Temat: Re: [sajjjadayobi/FaceLib] ShuffleneTiny model for Age-Gender estimation (#14)


you can train it with this code<https://github.com/sajjjadayobi/FaceLib/blob/master/facelib/AgeGender/models/train.py>
but use Tiny instead of Full
