### ISSUE TITLE
Nocorrect box coordinates

### ISSUE THREAD

**Issue by DimIsaev** [sajjjadayobi/FaceLib#15]
OS Win 10 / Python 3.8 

env
```
six               1.15.0
sklearn           0.0
threadpoolctl     2.1.0
tifffile          2021.4.8
toml              0.10.2
torch             1.8.1
torchvision       0.9.1
tqdm              4.60.0
typing-extensions 3.7.4.3
urllib3           1.26.4
```

![image](https://user-images.githubusercontent.com/11172642/115559471-f1046000-a2dd-11eb-9f07-c37117535552.png)

**Comment by sajjjadayobi** [comment]
I don't know what's happening 😄 
is this happen for all components or just Gender Detection?
please, send me your code
