### ISSUE TITLE
FaceLib on Nvidia Jetson Nano

### ISSUE THREAD

**Issue by dspinczyk** [sajjjadayobi/FaceLib#16]
I have tried to install on Nvidia Jetson Nano. It support bcolz 1.2.0 and matplotlib 2.1.1. Could you share the oldest version of FaceLib that support older version of package ( bcolz 1.2.0 and matplotlib 2.1.1) ?

**Comment by sajjjadayobi** [comment]
I don't have any older versions in terms of requirements
you can change `requirements.txt` to ( bcolz 1.2.0 and matplotlib 2.1.1) and test it 😄
I don't think it will be a problem

**Comment by dspinczyk** [comment]
Ok, I downgraded the package numbers in the locally downloaded version of the repository and used the pip install -e command.
Done, it's working. Thanks!
