### ISSUE TITLE
TypeError: infer() got multiple values for argument 'tta'

### ISSUE THREAD

**Issue by okoliechykwuka** [sajjjadayobi/FaceLib#22]
I captured an image using the `add_from_webcam`  function and stored it in a facebank folder with the specified person_name as a directory.
```

# from facelib import add_from_webcam

# add_from_webcam(person_name='chuks')
```

Now when I tried to verify the image in the folder using the `WebcamVerify` function.,It resulted to a TypeError. How can I fix this.?

```
from facelib import WebcamVerify
verifier = WebcamVerify(update=True)
verifier.run()
```

Error Traceback

```
"C:\Users\Desktop\FaceRec\Project\FaceLib\facelib\InsightFace\verifier.py", line 49, in run
    results, score = self.recognizer.infer(self.conf, faces, self.targets, tta=self.tta)
TypeError: infer() got multiple values for argument 'tta'
```

**Comment by sajjjadayobi** [comment]
sorry It was a bug in `infer` function, now it's fixed try again

**Comment by okoliechykwuka** [comment]
@sajjjadayobi Thanks for the prompt response. It working fine now.

Please I have a question, If I want to train on a custom dataset what directory do I need to store the image files, and what should be the directory structure.?

**Comment by sajjjadayobi** [comment]
Since my library is not suitable for training new models, I suggest using [this repo](https://github.com/TreB1eN/InsightFace_Pytorch)
