### ISSUE TITLE
some questions 

### ISSUE THREAD

**Issue by JH-Lam** [sajjjadayobi/FaceLib#26]
Hi , thanks your great job on this open project. there are some questions I confused , please give some  clues on them:
1. which sub dataset is used for training, the original wild or cropped? anyone is  viable?
2. why dont you use MoibleNet but ShuffleNet in Age and gender model? 
appreciate your effort again!

**Comment by sajjjadayobi** [comment]
Hi thank you, sorry I'm late.
 Answer to your first question: The original WILD
 Second one: At that time I didn't know MoibleNet is a better architecture, but 
 If I wanted to train the model again I would use  Efficientnet-b0

**Comment by JH-Lam** [comment]
thanks.
TBD: Do you think it's more reasonable to use cropped dataset to train the model so it'll gain higher accuracy?

**Comment by sajjjadayobi** [comment]
> 

Ye I think that's a reasonable thought 🤔

**Comment by JH-Lam** [comment]
sorry I'm a bit later.
Yes I just wonder what the landmarks are if an image is not a face when labels the training set? for instance, image1 is a cat, so it's class 0 ( class 1 belongs to face), and its landmarks should be all 0 ,-1 or others? what differences b/w these as to performance?
thanks a lot!

**Comment by sajjjadayobi** [comment]
Great question, but I never thought about or tested this one. I don't know what will happen.
have a try at it
p.s. give a star if the project was helpful

**Comment by JH-Lam** [comment]
You mean your training set are all about facial scenarios but no negative examples( eg. only a car on a road, flowers in the bottle etc) ? it seems weird since the model will *still* predict a face w/ landmarks even if it predicts on images without faces

This problem will not raise if splits one model to two: one for classifier , another is for regression on the positive result of former.
(ps : starred it)
