### ISSUE TITLE
Issue with EasyDict

### ISSUE THREAD

**Issue by padmalcom** [sajjjadayobi/FaceLib#28]
Hi, your requirements say EasyDict > 1.7.0 is required. I have 1.10.0 installed and get the following error:

  File "C:\Users\admin\anaconda3\envs\myproj\lib\site-packages\facelib\InsightFace\models\utils.py", line 11, in faces_preprocessing
    faces = faces.permute(0, 3, 1, 2).float()
AttributeError: 'EasyDict' object has no attribute 'permute'

Do you have any idea if the function has been renamed?

**Comment by sajjjadayobi** [comment]
faces must be PyTorch tensor
I think you have passed the wrong object as faces into this function

**Comment by padmalcom** [comment]
Yes thank you, I figured it out. I passed an empty list of faces, so I just had to check the length before.
