### ISSUE TITLE
Age & Gender Estimation

### ISSUE THREAD

**Issue by hsl8856** [sajjjadayobi/FaceLib#3]
How do you set the parameters of your training age and gender model?
batch_size, num_epochs, do you use a pre-trained model?

**Comment by sajjjadayobi** [comment]
this training code in my Colab. do you want it?
I can put it in the repo!

**Comment by hsl8856** [comment]
Ok thank you




| |
洪石林
|
|
邮箱：18855583063@163.com
|

签名由 网易邮箱大师 定制

On 07/26/2020 17:54, Sajjad Ayobi wrote:

this training code in my Colab. do you want it?
I can put it in the repo!

**Comment by sajjjadayobi** [comment]
already there is train.py for train age gender detection in AgeGender/models

**Comment by hsl8856** [comment]
thank you very much




| |
洪石林
|
|
邮箱：18855583063@163.com
|

签名由 网易邮箱大师 定制

On 07/26/2020 19:29, Sajjad Ayobi wrote:

already there is train.py for train age gender detection in AgeGender/models
