### ISSUE TITLE
pip install?

### ISSUE THREAD

**Issue by badjano** [sajjjadayobi/FaceLib#7]
I tried:
`pip install git+https://github.com/sajjjadayobi/FaceLib.git`
and also:
`python -m pip install git+https://github.com/sajjjadayobi/FaceLib.git`
Both did not work... it is kinda vague on the readme...
I did install this before but I can´t remember how I did it
Thanks

**Comment by badjano** [comment]
I just made your repository "installable" and will make a pull request with the modifications, you might want to check setup.py to see if everything is acceptable...

**Comment by sajjjadayobi** [comment]
thank you, it's amazing, check out my comment in the request session!!

**Comment by sajjjadayobi** [comment]
I merged your request 
if you have any time, correct imports issues in the readme file
thanks for your contribution
